<?php

/**
 * Implements hook_entity_presave().
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\file\FileInterface;

/**
 * Implements hook_entity_presave().
 */
function zero_importer_entity_presave(EntityInterface $entity) {
  // for files set changed to created
  if ($entity instanceof FileInterface) {
    $entity->changed = $entity->created;
  } else if (!empty($entity->original) && isset($entity->original->changed)) {
    $entity->changed = $entity->original->changed;
  }
}

/**
 * Implements hook_mail_alter().
 */
/**
 * Implements hook_mail_alter().
 */
function zero_importer_mail_alter(&$message) {
  // First: Prevent the mail from being sent.
  $message['send'] = FALSE;
}
